// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZPRDhfyzttEVfq9KCBYzbX7zBOaBEnY',
    appId: '1:486078244824:web:4b87c3c02d5bb8229334ad',
    messagingSenderId: '486078244824',
    projectId: 'food-delivery-fc42d',
    authDomain: 'food-delivery-fc42d.firebaseapp.com',
    storageBucket: 'food-delivery-fc42d.appspot.com',
    measurementId: 'G-JG51YKVDXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3I5r0N_D60DN2KfLOphjQZAsGTinarvA',
    appId: '1:486078244824:android:a4a1c8ba078a0a9e9334ad',
    messagingSenderId: '486078244824',
    projectId: 'food-delivery-fc42d',
    storageBucket: 'food-delivery-fc42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4apmqLImPQSMdK_HQndSW0uM3KK4Iyig',
    appId: '1:486078244824:ios:828ad67d1b6e35b89334ad',
    messagingSenderId: '486078244824',
    projectId: 'food-delivery-fc42d',
    storageBucket: 'food-delivery-fc42d.appspot.com',
    iosClientId: '486078244824-6021sn82do0vt1po47a8396imddr2fg0.apps.googleusercontent.com',
    iosBundleId: 'com.green.foodDeliveryGreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4apmqLImPQSMdK_HQndSW0uM3KK4Iyig',
    appId: '1:486078244824:ios:828ad67d1b6e35b89334ad',
    messagingSenderId: '486078244824',
    projectId: 'food-delivery-fc42d',
    storageBucket: 'food-delivery-fc42d.appspot.com',
    iosClientId: '486078244824-6021sn82do0vt1po47a8396imddr2fg0.apps.googleusercontent.com',
    iosBundleId: 'com.green.foodDeliveryGreen',
  );
}
